### PR TITLE
Wrapper overall improvement with support for generation, langdetection and tokens endpoints, unit and integration tests, custom status code errors...

### PR DESCRIPTION
**Pull request by pandatix**
This PR is :fire:**NOT BACKWARD COMPATIBLE**:fire:. Please make sure you create a new major version (tag) when merging it.

## What does this PR contains ?
 - :screwdriver: a fix for `nlpcloud.Question.Answer` invalid json tag value (`string` instead of `answer`)
 - :screwdriver: a fix for `nlpcloud.LibVersions` data structure
 - :screwdriver: a fix for optional parameters using pointers (optional means it can be not specified in a request, which means something different than being the default value of the underlying type. This is cleanly made possible using a pointer)
 - :superhero_man: an improvement of the `nlpcloud.Client` methods by using the same underlying function which follows the API specification
 - :superhero_man: an improvement of the `nlpcloud.Client` for interoperability, by giving it a sub-HTTP client to use for requests
 - :superhero_man: an improvement of the parameters given for each endpoint (except `LibVersions` which does not take some) using a data structure. This makes the API more cohesive and avoid having functions with a lot of parameters (this avoids shadowing the API)
 - :confetti_ball: the support of `nlpcloud.Client.Generation`, `nlpcloud.Client.LangDetection` and `nlpcloud.Client.Tokens` for their respective endpoints
 - :confetti_ball: the support for [documented errors](https://docs.nlpcloud.io/?shell#errors)
 - :microscope: unit tests for the whole module with a code coverage of 100%
 - :microscope: integration tests for the whole module
 - :checkered_flag: an update to Go 1.17
 - :checkered_flag: an update of the `README.md` to make it cleaner (not documenting each `nlpcloud.Client` endpoint while the website does it already, and the wrapper does it a second time to make sure it's properly understood). Add badges to prettify the doc.

## Discussions on the client interoperability
This PR claims to improve client interoperability by adding a parameter (the first) in the `nlpcloud.NewClient` function, which makes it not backward compatible. This one must be a valid `nlpcloud.HTTPClient`, which means it has to implement `Do(*http.Request) (*http.Response, error)`.
The code makes sure it works with a `*http.Client` while it will most often get used to achieve this task.

Nevertheless, specifying the underlying HTTP client to use enables the developer (the one who uses the wrapper) implementing strategies on the `Do` method, as a proxy, a status checker, a circuit breaker... as a middleware.

This directly enables integration tests which proves its use case is legitimate.

## Number of unit tests and integration tests
Looking at the unit and integration tests, you may think there are a lot of them for not so much. Indeed, there is a lot of duplications (e.g. to test custom status code errors).
Those duplications cannot be cleanly refactored in this state of Go while it would need generics for this. If you are trying to refactor this, you'll have to make an anonymous type to pass functions, making a wrapper for each one, passing the method as an argument with the parameters and expected results... which will make the tests a spaghetti code.

I do think it's better to get some duplications in tests than having an unreadable code.

## Additional comments
 - this PR needs you to create a GitHub secret for the `CODECOV_TOKEN` used by the CI (see https://app.codecov.io/gh/nlpcloud/nlpcloud-go using the repo owner account), and to set an `API_TOKEN` that is able to perform integration tests on the NLP Cloud API. Notice for this last that you'll need to make sure than the contribution guidelines follows a fork-PR strategy to avoid leaking it, and double-check when someone modify the `.github/workflows/ci.yaml` file.
 - the header `Content-type: application/json` is not checked by the server, as it should be according to the documentation of custom error `422 | Unprocessable Entity`
 - there is a typo in custom error `413 | Request Entity Too Large`: "i**t** too large" should be "i**s** too large"

### CODE REVIEW

**Comment by juliensalinas** [comment]
It looks like an impressive work @pandatix!
Let us review this ASAP!
Thanks a lot.

**Comment by juliensalinas** [comment]
Thanks again @pandatix, I just merged your PR!
Once again, it's an amazing client you built here, congrats. It's well documented, tested, perfectly follows the Go style, and seamlessly integrates all the subtleties of the NLP Cloud API 💪🏻 
It seems that integration tests break the Github CI because they require a valid API token. Maybe I should remove them from the Github workflows, what do you think?

**Comment by pandatix** [comment]
Hello, I'm glad that you liked my work and pleased to read that it perfectly fits into NLP Cloud API !
For the API token issue, you have two choices:
1. Remove the integration tests but you won't be able to detect breaking changes that are not supported by the wrapper
2. Create an API token in your server (maybe a service account used for CI) that is able to perform integration tests. In this last case make sure you double check future changes to the `.github.com/workflows/ci.yml` while someone could try to leak it (basically it's not supposed to change while this workflow already well covers the module)

**Comment by juliensalinas** [comment]
Thanks @pandatix !
I disabled the integration tests and I'll take some time to think about a good strategy. As this token will leak, we might want to enforce additional protection mechanism in order to avoid issues on the API side.

Thanks again!

**Pull request merged**
